// Sample Restaurant Dataset
// This simulates a CSV dataset with comprehensive restaurant information

const restaurantsData = [
  {
    id: 1,
    name: "Bella Italia",
    location: "Downtown, New York",
    cuisines: ["Italian", "Mediterranean"],
    rating: 4.5,
    cost_for_two: 45,
    veg: false,
    delivery: true,
    table_booking: true,
    reviews: "Authentic Italian cuisine with fresh pasta and wood-fired pizzas. Great ambiance and friendly service.",
    image_url: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&h=300&fit=crop",
    latitude: 40.7589,
    longitude: -73.9851
  },
  {
    id: 2,
    name: "Dragon Palace",
    location: "Chinatown, New York",
    cuisines: ["Chinese", "Asian"],
    rating: 4.2,
    cost_for_two: 35,
    veg: false,
    delivery: true,
    table_booking: false,
    reviews: "Best dim sum in town. Authentic Cantonese dishes with generous portions. Quick service.",
    image_url: "https://images.unsplash.com/photo-1525755662778-989d0524087e?w=400&h=300&fit=crop",
    latitude: 40.7158,
    longitude: -73.9970
  },
  {
    id: 3,
    name: "Spice Garden",
    location: "East Village, New York",
    cuisines: ["Indian", "Asian"],
    rating: 4.6,
    cost_for_two: 40,
    veg: true,
    delivery: true,
    table_booking: true,
    reviews: "Excellent vegetarian Indian food. Rich flavors and aromatic spices. Perfect naan bread.",
    image_url: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop",
    latitude: 40.7264,
    longitude: -73.9818
  },
  {
    id: 4,
    name: "Taco Fiesta",
    location: "Brooklyn, New York",
    cuisines: ["Mexican", "Latin American"],
    rating: 4.3,
    cost_for_two: 30,
    veg: false,
    delivery: true,
    table_booking: false,
    reviews: "Fresh tacos with homemade tortillas. Great guacamole and salsa. Casual atmosphere.",
    image_url: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=300&fit=crop",
    latitude: 40.6782,
    longitude: -73.9442
  },
  {
    id: 5,
    name: "Sakura Sushi",
    location: "Midtown, New York",
    cuisines: ["Japanese", "Asian"],
    rating: 4.7,
    cost_for_two: 60,
    veg: false,
    delivery: true,
    table_booking: true,
    reviews: "Premium sushi with fresh fish. Expert chefs and beautiful presentation. Worth the price.",
    image_url: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400&h=300&fit=crop",
    latitude: 40.7549,
    longitude: -73.9840
  },
  {
    id: 6,
    name: "Thai Orchid",
    location: "Queens, New York",
    cuisines: ["Thai", "Asian"],
    rating: 4.4,
    cost_for_two: 35,
    veg: false,
    delivery: true,
    table_booking: true,
    reviews: "Authentic Thai flavors with perfect spice levels. Pad Thai and green curry are excellent.",
    image_url: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=400&h=300&fit=crop",
    latitude: 40.7282,
    longitude: -73.7949
  },
  {
    id: 7,
    name: "The American Grill",
    location: "Times Square, New York",
    cuisines: ["American", "Grill"],
    rating: 4.1,
    cost_for_two: 50,
    veg: false,
    delivery: false,
    table_booking: true,
    reviews: "Classic American steakhouse. Great burgers and BBQ ribs. Large portions.",
    image_url: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=400&h=300&fit=crop",
    latitude: 40.7580,
    longitude: -73.9855
  },
  {
    id: 8,
    name: "Mediterranean Breeze",
    location: "Upper East Side, New York",
    cuisines: ["Mediterranean", "Greek"],
    rating: 4.5,
    cost_for_two: 45,
    veg: true,
    delivery: true,
    table_booking: true,
    reviews: "Fresh Mediterranean cuisine with excellent mezze platters. Healthy and delicious options.",
    image_url: "https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop",
    latitude: 40.7736,
    longitude: -73.9566
  },
  {
    id: 9,
    name: "Seoul Kitchen",
    location: "Manhattan, New York",
    cuisines: ["Korean", "Asian"],
    rating: 4.6,
    cost_for_two: 40,
    veg: false,
    delivery: true,
    table_booking: false,
    reviews: "Authentic Korean BBQ and bibimbap. Great kimchi and side dishes. Lively atmosphere.",
    image_url: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400&h=300&fit=crop",
    latitude: 40.7831,
    longitude: -73.9712
  },
  {
    id: 10,
    name: "Le Petit Bistro",
    location: "West Village, New York",
    cuisines: ["French", "European"],
    rating: 4.8,
    cost_for_two: 70,
    veg: false,
    delivery: false,
    table_booking: true,
    reviews: "Elegant French dining with exquisite wine selection. Perfect for special occasions.",
    image_url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop",
    latitude: 40.7358,
    longitude: -74.0036
  },
  {
    id: 11,
    name: "Veggie Delight",
    location: "SoHo, New York",
    cuisines: ["Indian", "Vegetarian"],
    rating: 4.4,
    cost_for_two: 30,
    veg: true,
    delivery: true,
    table_booking: false,
    reviews: "Pure vegetarian Indian restaurant with amazing paneer dishes and dal. Very affordable.",
    image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    latitude: 40.7233,
    longitude: -74.0030
  },
  {
    id: 12,
    name: "Pizza Paradise",
    location: "Little Italy, New York",
    cuisines: ["Italian", "Pizza"],
    rating: 4.3,
    cost_for_two: 35,
    veg: false,
    delivery: true,
    table_booking: false,
    reviews: "New York style pizza with thin crust and fresh mozzarella. Great for quick bites.",
    image_url: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop",
    latitude: 40.7195,
    longitude: -73.9977
  },
  {
    id: 13,
    name: "Wonton House",
    location: "Flushing, New York",
    cuisines: ["Chinese", "Noodles"],
    rating: 4.0,
    cost_for_two: 25,
    veg: false,
    delivery: true,
    table_booking: false,
    reviews: "Best wontons and noodle soups. Authentic Chinese flavors at great prices.",
    image_url: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=400&h=300&fit=crop",
    latitude: 40.7648,
    longitude: -73.8320
  },
  {
    id: 14,
    name: "Curry House",
    location: "Jackson Heights, New York",
    cuisines: ["Indian", "Curry"],
    rating: 4.2,
    cost_for_two: 32,
    veg: false,
    delivery: true,
    table_booking: true,
    reviews: "Excellent chicken curry and biryani. Spicy and flavorful with generous meat portions.",
    image_url: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=400&h=300&fit=crop",
    latitude: 40.7557,
    longitude: -73.8831
  },
  {
    id: 15,
    name: "Burrito Bowl",
    location: "Harlem, New York",
    cuisines: ["Mexican", "Fast Food"],
    rating: 3.9,
    cost_for_two: 22,
    veg: false,
    delivery: true,
    table_booking: false,
    reviews: "Quick Mexican food with customizable bowls. Good for lunch. Fresh ingredients.",
    image_url: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop",
    latitude: 40.8116,
    longitude: -73.9465
  },
  {
    id: 16,
    name: "Ramen Station",
    location: "East Village, New York",
    cuisines: ["Japanese", "Ramen"],
    rating: 4.5,
    cost_for_two: 38,
    veg: false,
    delivery: true,
    table_booking: false,
    reviews: "Rich tonkotsu ramen with perfectly cooked noodles. Long lines but worth the wait.",
    image_url: "https://images.unsplash.com/photo-1557872943-16a5ac26437e?w=400&h=300&fit=crop",
    latitude: 40.7295,
    longitude: -73.9876
  },
  {
    id: 17,
    name: "Pho 88",
    location: "Chinatown, New York",
    cuisines: ["Thai", "Vietnamese"],
    rating: 4.1,
    cost_for_two: 28,
    veg: false,
    delivery: true,
    table_booking: false,
    reviews: "Authentic Vietnamese pho with aromatic broth. Large bowls and very affordable.",
    image_url: "https://images.unsplash.com/photo-1591814468924-caf88d1232e1?w=400&h=300&fit=crop",
    latitude: 40.7164,
    longitude: -73.9960
  },
  {
    id: 18,
    name: "Steakhouse Prime",
    location: "Midtown, New York",
    cuisines: ["American", "Steakhouse"],
    rating: 4.7,
    cost_for_two: 85,
    veg: false,
    delivery: false,
    table_booking: true,
    reviews: "Premium steaks cooked to perfection. Upscale dining with impeccable service.",
    image_url: "https://images.unsplash.com/photo-1558030006-450675393462?w=400&h=300&fit=crop",
    latitude: 40.7614,
    longitude: -73.9776
  },
  {
    id: 19,
    name: "Olive Garden Express",
    location: "Brooklyn, New York",
    cuisines: ["Mediterranean", "Italian"],
    rating: 4.0,
    cost_for_two: 38,
    veg: true,
    delivery: true,
    table_booking: true,
    reviews: "Fresh salads and pasta dishes. Good vegetarian Mediterranean options.",
    image_url: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop",
    latitude: 40.6501,
    longitude: -73.9496
  },
  {
    id: 20,
    name: "Seoul BBQ",
    location: "Koreatown, New York",
    cuisines: ["Korean", "BBQ"],
    rating: 4.6,
    cost_for_two: 48,
    veg: false,
    delivery: false,
    table_booking: true,
    reviews: "Interactive Korean BBQ experience. High quality meats and excellent banchan.",
    image_url: "https://images.unsplash.com/photo-1588348565750-f3df7a3f9067?w=400&h=300&fit=crop",
    latitude: 40.7484,
    longitude: -73.9857
  }
];

// User's current location (default: Manhattan, NY)
const userLocation = {
  latitude: 40.7580,
  longitude: -73.9855
};